services:
  api:
    build:
      context: "."
      dockerfile: "Dockerfile"
      target: "dev"
    command: dev
    environment:
      PRIVATE_KEY: ./tmp/private.pem
      PUBLIC_KEY: ./tmp/public.pem
      DB_HOST: db
    depends_on:
      - "db"
    ports:
      - "8000:8000"
      - "5678:5678"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
    - 5432:5432
