"""Check

Revision ID: 9d883eba144b
Revises: 7af9ed032b40
Create Date: 2025-01-10 20:55:24.813302

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy_utc import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = "9d883eba144b"
down_revision: Union[str, None] = "7af9ed032b40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "check",
        sa.Column("created_on", UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_on", UtcDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_check_id"), "check", ["id"], unique=False)
    op.create_table(
        "payment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("CACHE", "CACHLESS", name="paymenttyps"), nullable=False
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("check_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["check_id"],
            ["check.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payment_id"), "payment", ["id"], unique=False)
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("check_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["check_id"],
            ["check.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_id"), "product", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_id"), table_name="product")
    op.drop_table("product")
    op.drop_index(op.f("ix_payment_id"), table_name="payment")
    op.drop_table("payment")
    op.drop_index(op.f("ix_check_id"), table_name="check")
    op.drop_table("check")
    # ### end Alembic commands ###
