"""Check add total and rest field

Revision ID: b13fbb846e99
Revises: 9d883eba144b
Create Date: 2025-01-10 21:01:29.372195

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b13fbb846e99"
down_revision: Union[str, None] = "9d883eba144b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("check", sa.Column("total", sa.Integer(), nullable=False))
    op.add_column("check", sa.Column("rest", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("check", "rest")
    op.drop_column("check", "total")
    # ### end Alembic commands ###
