"""Change relation in check

Revision ID: b509c684d2fa
Revises: 2e87a02be7f2
Create Date: 2025-01-11 09:12:15.000739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b509c684d2fa'
down_revision: Union[str, None] = '2e87a02be7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'check', ['payment_id'])
    op.create_foreign_key(None, 'check', 'payment', ['payment_id'], ['id'])
    op.drop_constraint('payment_check_id_fkey', 'payment', type_='foreignkey')
    op.drop_column('payment', 'check_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('check_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('payment_check_id_fkey', 'payment', 'check', ['check_id'], ['id'])
    op.drop_constraint(None, 'check', type_='foreignkey')
    op.drop_constraint(None, 'check', type_='unique')
    op.drop_column('check', 'payment_id')
    # ### end Alembic commands ###
