"""new indexs

Revision ID: be0e0466d4b1
Revises: d56e5f7c79b3
Create Date: 2025-01-17 10:09:23.520473

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be0e0466d4b1"
down_revision: Union[str, None] = "d56e5f7c79b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_check_total"), "check", ["total"], unique=False)
    op.create_index(op.f("ix_payment_type"), "payment", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_type"), table_name="payment")
    op.drop_index(op.f("ix_check_total"), table_name="check")
    # ### end Alembic commands ###
