"""Add index

Revision ID: d56e5f7c79b3
Revises: 9d286eeb033f
Create Date: 2025-01-17 09:27:53.972001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd56e5f7c79b3'
down_revision: Union[str, None] = '9d286eeb033f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('created_at_index', 'check', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('created_at_index', table_name='check')
    # ### end Alembic commands ###
